# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.

# param {String} s
# param {String} t
# return {Character}
def find_the_difference(s, t)
    s_sort = s.split('').sort
    t_sort = t.split('').sort
    t_sort.each_with_index {|char,i| return char if s_sort[i] != char }
end